# Generated by Django 5.0 on 2024-01-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllUsers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='HouseUnit',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
