# Generated by Django 5.0 on 2024-01-25 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllUsers', '0002_customuser_houseunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPaymentModel',
            fields=[
                ('InvoiceID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('PaymentAmount', models.CharField(max_length=20)),
                ('InvoiceImage', models.ImageField(blank=True, null=True, upload_to='payment/')),
                ('userID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payment',
            },
        ),
    ]
