# Generated by Django 5.0 on 2024-01-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllUsers', '0004_alter_customuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpaymentmodel',
            name='InvoiceDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userpaymentmodel',
            name='InvoiceTime',
            field=models.TimeField(auto_now=True),
        ),
    ]
