# Generated by Django 5.0 on 2024-01-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllUsers', '0006_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpaymentmodel',
            name='paid',
            field=models.BooleanField(default=1, verbose_name=0),
            preserve_default=False,
        ),
    ]
