# Generated by Django 5.0 on 2024-01-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllUsers', '0007_userpaymentmodel_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpaymentmodel',
            name='paid',
            field=models.BooleanField(verbose_name='paid?'),
        ),
    ]
