# Generated by Django 5.0 on 2024-01-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllUsers', '0008_alter_userpaymentmodel_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpaymentmodel',
            name='PaymentAmount',
            field=models.CharField(default='RM', max_length=20),
        ),
    ]
