# Generated by Django 5.0 on 2024-01-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllUsers', '0009_alter_userpaymentmodel_paymentamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpaymentmodel',
            name='PaymentAmount',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
