# Generated by Django 5.0 on 2024-01-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllUsers', '0010_alter_userpaymentmodel_paymentamount'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadPaymentModel',
            fields=[
                ('PaymentID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('PaymentImage', models.FileField(blank=True, null=True, upload_to='payment/Inovice/')),
            ],
            options={
                'verbose_name': 'Payment Upload',
                'verbose_name_plural': 'Payment Upload',
            },
        ),
    ]
