# Generated by Django 5.0 on 2024-01-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllUsers', '0011_uploadpaymentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ParkingLot',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
