# Generated by Django 5.0 on 2024-01-29 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllUsers', '0012_customuser_parkinglot'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadpaymentmodel',
            name='userID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
