# Generated by Django 5.0 on 2024-01-31 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AllUsers', '0013_uploadpaymentmodel_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadpaymentmodel',
            name='userID',
        ),
    ]
