# Generated by Django 5.0 on 2024-01-31 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllUsers', '0014_remove_uploadpaymentmodel_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadpaymentmodel',
            name='username',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
