# Generated by Django 5.0 on 2024-01-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeScheduleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SchedulePostDate', models.DateField(auto_now=True)),
                ('SchedulePostTime', models.TimeField(auto_now=True)),
                ('ScheduleNote', models.TextField()),
                ('ScheduleImage', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Employee Schedule',
                'verbose_name_plural': 'Employee Schedule',
            },
        ),
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feedback', models.TextField()),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
            },
        ),
        migrations.CreateModel(
            name='NoticeBoardModel',
            fields=[
                ('NoticeBoardID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('NoticeTitle', models.TextField()),
                ('NoticeDescription', models.TextField()),
                ('NoticeDate', models.DateField(auto_now=True)),
                ('NoticeTime', models.TimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notice Board',
                'verbose_name_plural': 'Notice Board',
            },
        ),
        migrations.CreateModel(
            name='RegisterForm',
            fields=[
                ('VisitorID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('noPlate', models.CharField(max_length=10, verbose_name='no Plate')),
                ('LicenseNum', models.CharField(max_length=12)),
                ('CarModel', models.CharField(max_length=30)),
                ('PhoneNum', models.CharField(max_length=13)),
                ('DateTime', models.CharField(max_length=20)),
                ('CarNum', models.CharField(max_length=20)),
                ('HouseUnit', models.CharField(max_length=5)),
                ('leave', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Visitor',
                'verbose_name_plural': 'Visitor',
            },
        ),
    ]
