# Generated by Django 5.0 on 2024-01-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeResidentSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeschedulemodel',
            name='SchedulePostDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employeeschedulemodel',
            name='SchedulePostTime',
            field=models.TimeField(),
        ),
    ]
