# Generated by Django 5.0 on 2024-01-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeResidentSystem', '0002_alter_employeeschedulemodel_schedulepostdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeschedulemodel',
            name='id',
        ),
        migrations.AddField(
            model_name='employeeschedulemodel',
            name='ScheduleID',
            field=models.AutoField(default=1, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeeschedulemodel',
            name='SchedulePostDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employeeschedulemodel',
            name='SchedulePostTime',
            field=models.TimeField(auto_now=True),
        ),
    ]
