# Generated by Django 5.0 on 2024-01-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeResidentSystem', '0003_remove_employeeschedulemodel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeschedulemodel',
            name='ScheduleImage',
            field=models.ImageField(blank=True, null=True, upload_to='schedule/'),
        ),
    ]
