# Generated by Django 5.0 on 2024-01-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeResidentSystem', '0004_alter_employeeschedulemodel_scheduleimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticeboardmodel',
            name='NoticeImage',
            field=models.ImageField(blank=True, null=True, upload_to='notice/'),
        ),
    ]
