# Generated by Django 5.0 on 2024-01-27 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeResidentSystem', '0006_paymentmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentModel',
        ),
    ]
