# Generated by Django 5.0 on 2024-01-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeResidentSystem', '0007_delete_paymentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmodel',
            name='FeedbackImage',
            field=models.ImageField(blank=True, null=True, upload_to='feedback/'),
        ),
    ]
